name: tesora
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  http: ^1.2.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.3
  get_it: ^7.7.0
  provider: ^6.1.2
  go_router: ^14.2.0
  flutter_native_splash: ^2.1.9
  auto_size_text: ^3.0.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  lottie: ^1.2.1
  flutter_localization: ^0.3.0
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.1
  google_mlkit_entity_extraction: ^0.13.1
  image_editor_plus: ^1.0.5
  flutter_speed_dial: ^4.4.0
  flutter_animate: ^4.5.0
  image: ^4.1.7
  image_gallery_saver: ^2.0.3
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  timezone: ^0.9.0
  fluttertoast: ^8.2.10

  tutorial_coach_mark: ^1.2.12
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0
  flutter_gen: ^5.6.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/app/images/logo_tesoreria.png"

flutter:

  uses-material-design: true

  assets:
    - lib/app/images/
    - assets/mock/mobile/secin/
    - assets/mock/mobile/sec/
    - assets/mock/mobile/sec/restablecer/pass/
    - assets/mock/mobile/inversiones/
    - assets/mock/mobile/autorizacion/
    - assets/mock/mobile/procesa/
    - assets/mock/mobile/cuenta/
    - assets/mock/mobile/
    - assets/imagenes/iconos/
    - assets/imagenes/menu/
    - assets/imagenes/
    - assets/mock/mobile/cuentas/propias/
    - assets/mock/mobile/
    - assets/mock/mobile/directorio/
    - assets/mock/mobile/usuario/
    - assets/mock/gateway/api/authentication/
