// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByewnDFtx7cXLKWjkmW4IADqtNlsm7kuQ',
    appId: '1:138230862683:web:c2c1086cb27e0810e8407e',
    messagingSenderId: '138230862683',
    projectId: 'tesoramobil',
    authDomain: 'tesoramobil.firebaseapp.com',
    storageBucket: 'tesoramobil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmeJYKBvqcIewnfEk3dGKVNaVA4w0_jtk',
    appId: '1:138230862683:android:488fc96d98f9e498e8407e',
    messagingSenderId: '138230862683',
    projectId: 'tesoramobil',
    storageBucket: 'tesoramobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8R0IxFTj3JgVkF8FPrCVkriV1ZZT1Z8',
    appId: '1:138230862683:ios:01647903b56904f6e8407e',
    messagingSenderId: '138230862683',
    projectId: 'tesoramobil',
    storageBucket: 'tesoramobil.firebasestorage.app',
    iosBundleId: 'com.tesora.tesora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8R0IxFTj3JgVkF8FPrCVkriV1ZZT1Z8',
    appId: '1:138230862683:ios:01647903b56904f6e8407e',
    messagingSenderId: '138230862683',
    projectId: 'tesoramobil',
    storageBucket: 'tesoramobil.firebasestorage.app',
    iosBundleId: 'com.tesora.tesora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByewnDFtx7cXLKWjkmW4IADqtNlsm7kuQ',
    appId: '1:138230862683:web:a41e897276e3d601e8407e',
    messagingSenderId: '138230862683',
    projectId: 'tesoramobil',
    authDomain: 'tesoramobil.firebaseapp.com',
    storageBucket: 'tesoramobil.firebasestorage.app',
  );
}
